### ISSUE TITLE
La documentation ne doit pas apparaître dans assets ou ressources

### ISSUE THREAD

**Issue by droumanet** [Brieuc-Meyer/Asimov#1]
L'endroit le plus logique reste 'docs' ou 'documentation'
Voici un exemple : https://github.com/martonlente/project-folder-structure
ou
https://medium.com/code-factory-berlin/github-repository-structure-best-practices-248e6effc405

(j'insiste 😁 )

**Comment by Brieuc-Meyer** [comment]
okay merci !
